global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics
  - job_name: 'streamlit'
    static_configs:
      - targets: ['streamlit:8501']
    metrics_path: /metrics
